export const data = [
  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
  "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.  Richard McClure, a professor of history at Hampden-Sydney College, wrote in his 1915 book 'The Adventures of Tom Sawyer' that 'It is a truth universally acknowledged, that the only thing more dangerous than ignorance is arrogance.'",
  "The quick brown fox jumps over the lazy dog. Dorothy had a great time at the zoo. The cat sat on the mat. The dog chased the fox. The fox jumped over the dog. The dog chased the cat. The cat sat on the mat. The dog chased the fox. The fox jumped over the dog.",

  "In a village in the heart of the country, there lived a farmer named Bob. He had a beautiful garden with flowers, trees, and a small pond. He loved to play with his friends, and he was always the first to come home with his favorite toys. One day, Bob saw a beautiful fox playing in the pond. He decided to take the fox home with him for a while. He walked all the way to the fox, and when he got to the pond, he saw the fox playing. Bob felt a strange sensation in his stomach. He realized that the fox had eaten something in the pond. He went to the pond and saw a small, tasty fish. He ate the fish and felt better.",
  "The quick brown fox jumps over the lazy dog. Dorothy had a great time at the zoo. The cat sat on the mat. The dog chased the fox. The fox jumped over the dog. The dog chased the cat. The cat sat on the mat. The dog chased the fox. The fox jumped over the dog.",
  "In a village in the heart of the country, there lived a farmer named Bob. He had a beautiful garden with flowers, trees, and a small pond. He loved to play with his friends, and he was always the first to come home with his favorite toys. One day, Bob saw a beautiful fox playing in the pond. He decided to take the fox home with him for a while. He walked all the way to the \
  fox, and when he got to the pond, he saw the fox playing. Bob felt a strange sensation in his stomach. He realized that the fox had eaten something in the pond. He went to the pond and saw a small, tasty fish. He ate the fish and felt better.",
  "The quick brown fox jumps over the lazy dog. Dorothy had a great time at the zoo. The cat sat\
  on the mat. The dog chased the fox. The fox jumped over the dog. The dog chased the cat. The cat sat on the mat. The dog chased the fox. The fox jumped over the dog.",
  "In a village in the heart of the country, there lived a farmer named Bob. He had a beautiful garden with flowers, trees, and a small pond. He loved to play with his friends",
  "Bob was always the first to come home with his favorite toys. One day, Bob saw a beautiful fox playing in the pond. He decided to take the fox home with him for a while. He walked all the way to the fox, and when he got to the pond, he saw the fox playing. Bob felt a strange sensation in his stomach. He realized that the fox had eaten something in the pond. He went\
  to the pond and saw a small, tasty fish. He ate the fish and felt better.",
  "The quick brown fox jumps over the lazy dog. Dorothy had a great time at the zoo. The cat sat on the mat. The dog chased the fox. The fox jumped over the dog. The dog chased the cat. The cat sat on the mat. The dog chased the fox. The fox jumped over",

  "The quick brown fox jumps over the lazy dog. Dorothy had a great time at the zoo. The cat sat on the mat. The dog chased the fox. The fox jumped over the dog. The dog chased the cat. The cat sat on the mat. The dog chased the fox. The fox jumped over the dog.",
  "In a village in the heart of the country, there lived a farmer named Bob. He had a beautiful garden with flowers, trees, and a small pond. He loved to play with his friends, and he was always the first to come home with his favorite toys. One day, Bob saw a beautiful fox playing in the pond. He decided to take the fox home with him for a while. He walked all the way to the fox, and when he got to the pond, he saw the fox playing. Bob felt a strange sensation in his stomach. He realized that the fox had eaten something in the pond. He went to the pond and saw a small, tasty fish. He ate the fish and felt better.",
  "The quick brown fox jumps over the lazy dog. Dorothy had a great time at the zoo. The cat sat on the mat. The dog chased the fox. The fox jumped over the dog. The dog chased the cat. The cat sat on the mat. The dog chased the fox. The fox jumped over the dog.",

  "In a village in the heart of the country, there lived a farmer named Bob. He had a beautiful garden with flowers, trees, and a small pond. He loved to play with his friends, and he was always the first to come home with his favorite toys. One day, Bob saw a beautiful fox playing in the pond. He decided to take the fox home with him for a while. He walked all the way to the fox, and when he got to the pond, he saw the fox playing. Bob felt a strange sensation in his stomach. He realized that the fox had eaten something in the pond."
]